### ISSUE TITLE
Playground -> issue credential not working

### ISSUE THREAD

**Issue by dirkcuys** [digitalcredentials/designer#27]
When trying to issue a credential on the playground, the request to https://sign-and-verify.herokuapp.com/issue/credentials fails with the following error in both firefox and chromium:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sign-and-verify.herokuapp.com/issue/credentials. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 503

**Comment by kezike** [comment]
Hey Dirk! The instance of `sign-and-verify` at https://sign-and-verify.herokuapp.com is outdated. I have an instance running at https://kezike-sign-and-verify.herokuapp.com, which is the default instance we are using in the `main` branch, as seen [here](https://github.com/digitalcredentials/playground/blob/master/src/utils/config.ts#L17). You are seeing this issue in GitHub Pages, because that app has not yet been updated to point to the `main` branch. Until we make that update, you are free to run this app locally by following the instructions [here](https://github.com/digitalcredentials/playground#readme). Hope this helps!

**Comment by dirkcuys** [comment]
Thanks, that helps a lot! There were a few missing dependencies, but it's up and running now and I see there is already a [PR](https://github.com/digitalcredentials/playground/pull/25/files) for the missing deps!

**Comment by dirkcuys** [comment]
It seems like "Request Demo Credential" is not working on https://kezike-sign-and-verify.herokuapp.com/. Looking at the network request in the "web developer tools" I see the request returning the following error:

```json
{"statusCode":500,"error":"Internal Server Error","message":"Something went wrong"}
```

Is there something special I need to do the request a credential?

**Comment by dmitrizagidulin** [comment]
Closing the issue for the moment (since we're re-writing the sandbox)
